Lecture 4 task, simple_chat application
rbkmoney/erlang-school pull request #12
Opened 2018-08-03 11:17 UTC by 4tyTwo

Некоторые из замечаний к предыдущему пул реквесту не были исправлены:
1) Определение параметров супервайзера обязательно, исходя из документации.
2) io:format в get messages сообщений нужен для красивого вывода их в консоль.
3)Параметры супервизора ботов нуждаются в определении стратегии one for one исходя из логики работы ботов, они должны быть изолированы друг от друга и перезапускается по одиночке.

2018-08-13 13:57 UTC, 4tyTwo commented
Добавил чат на tcp сокетах. Выполнен максимально просто: сервер запускается вместе с приложением из его супервайзера, пользователь подключается к серверу и получает свой PID для взаимодействия с ним, на сервере в свою очередь пользователю выделяется свободный сокет. Пользователь может отправлять сообщения и получать сообщения от сервера.

2018-08-16 14:21 UTC, petrkozorezov requested changes
Схема некорректна. Нужно разделить клиент и сервер на разные ноды, и отделить комнату от работы TCP.

2018-08-16 14:21 UTC, petrkozorezov commented on tcp_chat/rebar.config
> +     ]}.
Поехало форматирование (и не только тут 😉)

2018-08-16 14:21 UTC, petrkozorezov commented on tcp_chat/src/tcp_chat_sup.erl
> +        intensity => 0,
Почему такие числа? Дефолтные не подходят?

2018-09-21 08:50 UTC, keynslug commented on chat/apps/chat_client/app.config
> +{lager, [
А какую роль этот файл выполняет?

2018-09-21 08:50 UTC, keynslug commented on chat/apps/chat_client/src/chat_client_client.erl
> +    {ok, _} = gen_server:start_link({global, Id}, ?MODULE, <<"Incognito">>, []).
Немного смущает хардкод имени пользователя, почему бы не вынести в параметры функции?

2018-09-21 08:50 UTC, keynslug commented on chat/apps/chat_client/src/chat_client_client.erl
> +        Json = library_protocol:encode({send_message, <<>>, Message, RoomId}),
Кажется что-то с индентацией.

2018-09-21 08:50 UTC, keynslug commented on chat/apps/chat_client/src/chat_client_client.erl
> +    ok = lager:info("Sending message ~p throught websocket", [Message]),
Если у тебя тут не один раз встречается паттерн _отлогировать и послать сообщение_, почему бы не вынести в отдельную функцию?

2018-09-21 08:50 UTC, keynslug commented on chat/apps/chat_client/src/chat_client_client.erl
> +    {ok, _} = gen_server:start_link({global, Id}, ?MODULE, <<"Incognito">>, []).
Ещё непонятно, почему `{global, Id}`? Почему недостаточно `{local, Id}`? И нужно ли вообще именовать процесс?

2018-09-21 08:50 UTC, keynslug commented on chat/apps/chat_client/src/chat_client_client.erl
> +-type joined_state() :: state(joined).
А клиент может присоединиться более чем к одной _комнате_?

2018-09-21 08:50 UTC, keynslug commented on chat/apps/chat_client/src/chat_client_client.erl
> +            ok = io:fwrite("~p: ~p~n", [binary_to_list(Username), binary_to_list(Message)]);
А почему не `lager:debug` и ему подобные?

2018-09-21 08:50 UTC, keynslug commented on chat/apps/chat_client/src/chat_client_client.erl
> +    ok = lager:info("Sending message ~p throught websocket", [Message]),
И ещё один момент: в таких местах нужно с уровнем логирования определяться. Если это для информирования операторов системы, то это `info`. Если это для тебя, чтобы понимать что происходит в процессе разработки, то это `debug` всё же.

2018-09-21 08:50 UTC, keynslug commented on chat/apps/chat_client/src/chat_client_client.erl
> +    #{messageList := MessageList} = State,
Внезапный camelCase подъехал почему-то.

2018-09-21 08:50 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_sup.erl
> +        intensity => 10,
А почему именно такие числа, почему например не дефолтные?

2018-09-21 08:50 UTC, keynslug commented on chat/apps/library/Test/library_SUITE.erl
> +encodeJson(_C) ->
Внезапный camelCase опять.

2018-09-21 08:50 UTC, keynslug commented on chat/apps/library/src/library_chatlib.erl
> +-export([is_in_list/2]).
А чем тебе не подошёл `lists:member/2` для этой задачи?

2018-09-21 08:50 UTC, keynslug commented on chat/config/app.config
> +{lager, [
И какая роль у этого файла в репозитории?

2018-09-21 08:50 UTC, keynslug commented on chat/docker-compose.yml
> +        image: redis
Ого, а зачем он тут?

2018-09-21 08:50 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_room_manager.erl
> +-spec handle_cast(term(), State :: stateless) ->
Но `State` – это же пустой список у тебя, спека точно правильная?

2018-09-25 14:47 UTC, keynslug commented on chat/apps/chat_client/src/chat_client_client.erl
> +    ok = gen_server:call({global, Id}, {create, RoomId}).
А тут разве не могут быть бизнес-ошибки, например для случая, когда комната уже существует?

2018-09-27 09:47 UTC, keynslug commented on chat/apps/chat_client/src/chat_client_client.erl
> +    ok = lager:debug("User ~p called get_last_message", [PID]),
А почему `User ~p ...` в качестве сообщения? Ведь это просто pid клиентского процесса.

2018-09-27 09:47 UTC, keynslug commented on chat/apps/chat_client/src/chat_client_client.erl
> +    {ok, #{connected => false, host => "localhost", port => 8080, username => ?DEFAULT_USERNAME, message_list => []}}.
О, а почему ты хардкодишь host и port?

2018-09-27 09:47 UTC, keynslug commented on chat/apps/chat_client/src/chat_client_client.erl
> +    {[], []};
А почему ты в качестве Head решил возвращать пустой список?

2018-09-27 09:47 UTC, keynslug commented on chat/apps/chat_client/src/chat_client_client.erl
> +    ok = lager:info("Adding message ~p to message list", [Message]),
Вот здесь хороший пример: ровно за строчку до вызова этой функции происходит логирование того же самого сообщения. Это значит, что в подавляющем большинстве случаев (за исключением разве что прилёта процессу beam SIGKILL'а) в логах будут две записи примерно об одном и том же.

Это на мой взгляд немного ухудшает информативность логов, потому что объём информационного шума в них повышается.

2018-09-27 09:47 UTC, keynslug commented on chat/apps/chat_server/Test/server_SUITE.erl
> +    timer:sleep(?DEFAULT_SLEEP), % Give server time to respond
Вот это тоже не самый здоровый признак: полагаться на таймауты в тестах. Все этим грешат, в том числе многие наши проекты, что постоянно приводит к флапающим тестам и бессмысленным коммитам, которые играются с размером таймаутов. У тебя нет тут возможности полагаться на какие-то детерминированно возникающие события?

Если нет, то уже будет лучше, если ты будешь не один раз пытаться получить сообщение с клиента, а несколько раз до победного конца, где _число раз_ и _задержка_ между попытками будут разумно подобранными параметрами. Можно даже написать функцию высшего порядка, реализующую подобную стратегию для тестов.

2018-09-27 09:47 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_room_manager.erl
> +-spec handle_cast(term(), RoomList :: list()) ->
А почему не `[binary()]`, как в https://github.com/rbkmoney/erlang-school/pull/12/files/521ac840ba9490d254b4d7414e1c3a0c321037f2..e6a86b90c7d21138d111ab8d9a8b4c09b8db47a5#diff-c585698924a60286a9f22a9f0555617cR45 ? Я бы даже предложил всегда локальные типы для таких вещей вводить.

2018-09-27 09:47 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_sup.erl
> +        intensity => 1,
Эти ассоциации вообще тогда можно убрать, чтобы переложить ответственность за выбор значений на OTP. 🙃

2018-09-27 09:47 UTC, keynslug commented on chat/docker-compose.yml
> -version: "3"
Да, это жёстко. 🔥 Я вообще только про редис спрашивал.

2018-09-27 16:29 UTC, keynslug commented on chat/apps/chat_client/src/chat_client_client.erl
> +-type pending() :: {from(), library_protocol:source_message()} | empty.
Если твой стейт здесь – это `map()`, то моделировать `... | empty` по идее правильнее в виде отсутствия ключа `pending` в мапе.

2018-09-27 16:29 UTC, keynslug commented on chat/apps/chat_client/src/chat_client_client.erl
> +    {ok, #{connected => false, host => Host, port => Port, username => ?DEFAULT_USERNAME, message_list => [], pending => empty}}.
Та же самая тема (про моделирования отсутствия состояния) и про `connected` вот здесь. К тому же непонятно, зачем тебе бит информации `connected := true | false`, если у тебя есть поле `pid` в стейте.

2018-09-27 16:29 UTC, keynslug commented on chat/apps/chat_client/src/chat_client_client.erl
> +    ({active_event() | set_username, RoomId :: binary()}, _From :: from(), State :: state()) ->
Я это невольно читаю как `{active_event(), RoomId} | {set_username, RoomId}` и как следствие у меня возникает вопрос, что значит `{set_username, RoomId}`? 🙃

2018-09-27 16:29 UTC, keynslug commented on chat/apps/chat_client/src/chat_client_client.erl
> +    ({active_event() | set_username, RoomId :: binary()}, _From :: from(), State :: state()) ->
Кстати, я же не раз видел тип для имени комнаты, почему бы не определить его в библиотечном приложении? Как и некоторые другие кстати вещи.

2018-09-27 16:29 UTC, keynslug commented on chat/apps/chat_client/src/chat_client_client.erl
> +    {noreply, NewState, ?DEFAULT_TIMEOUT};
А зачем ты здесь ставишь таймер на `?DEFAULT_TIMEOUT`?

2018-09-27 16:29 UTC, keynslug commented on chat/apps/chat_client/src/chat_client_client.erl
> +handle_request(send_message, Text, RoomId, From, #{username := Username} = State) ->
Функции `handle_request/4,5` выглядят крайне похожими. Может диссонанс в том, что `Text` не является частью _типа_ сообщения? Что если _тип_ сообщений выражался бы как `join | leave | ... | {message, Text}`?

2018-09-27 16:29 UTC, keynslug commented on chat/apps/chat_client/src/chat_client_client.erl
> +        {library_protocol:source_message() | empty, list()}.
Негласным соглашением в среде Erlang-разработчиков, по крайней мере у нас, является выражение отсутствия чего-либо атомом `undefined`.

2018-09-27 16:29 UTC, keynslug commented on chat/apps/chat_server/Test/server_SUITE.erl
> +    {ok, PID} = chat_client_client:start_link(?HOST, ?PORT),
По идее в тестах у тебя должна быть возможность выбрать любой host и port (например по стратегии _первый свободный_, но я не предлагаю тебе её имплементировать), и запустить на нём и _сервер_, и подключиться _клиентом_.

2018-09-27 16:29 UTC, keynslug commented on chat/apps/chat_server/Test/server_SUITE.erl
> +-define(USER,      <<"Igor">>).
Минидокоп: а чего у тебя директория `Test` с большой буквы? )

2018-09-27 16:29 UTC, keynslug commented on chat/apps/chat_client/src/chat_client_client.erl
> +match_error(Message) ->
А почему кстати этот кусок вместе со всеми дефайнами не в library?

2018-09-28 07:53 UTC, 4tyTwo commented on chat/apps/chat_server/Test/server_SUITE.erl
> +-define(USER,      <<"Igor">>).
Cтранно, на моей машине папка называется именно test. Название Test использовалось очень давно. Почитал и оказалось, что из-за особенностей Mac OS, git не чувствителен к подобным переименованиям (https://coderwall.com/p/mgi8ja/case-sensitive-git-in-mac-os-x-like-a-pro). ¯\_(ツ)_/¯

2018-09-28 11:27 UTC, keynslug commented on chat/apps/chat_server/Test/server_SUITE.erl
> +-define(USER,      <<"Igor">>).
Лол. А `git mv Test test` сработает?

2018-09-28 11:47 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_room_manager.erl
> +-spec room_exists(RoomRoomId :: library_protocol:room()) ->
_Vroom Vroom_? )

2018-09-28 12:10 UTC, 4tyTwo commented on chat/apps/chat_server/Test/server_SUITE.erl
> +-define(USER,      <<"Igor">>).
Так вроде тоже не сработает, у меня получилось переименовать в два этапа через третье имя

2018-09-28 14:09 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_sup.erl
> +    ok = lager:notice("Launched cowboy on ~p:~p", [Host, Port]),
Мне кажется, или `Host` не используется нигде, кроме как в лог-сообщении?

2018-09-28 14:11 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_app.erl
> +    ok = lager:debug("Args are ~p", [Args]),
Ого, это кстати крайне редко используемый нами паттерн. Посмотри лучше на `application:get_env/2,2`, `application:get_all_env/1`, вот это гораздо более часто используемый паттерн для daemonlike приложений на erlang.

2018-10-03 07:16 UTC, 4tyTwo commented on chat/apps/chat_server/src/chat_server_sup.erl
> +    ok = lager:notice("Launched cowboy on ~p:~p", [Host, Port]),
Используется на 34 строке, внутри cowboy_router:compile

2018-10-03 08:11 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_sup.erl
> +    ok = lager:notice("Launched cowboy on ~p:~p", [Host, Port]),
А, прикол, никогда эту штуку не использовал, вообще туда не подумал. 🙃  А как ты считаешь, какого эффекта ты достигаешь, указывая там заданный извне `Host`?

2018-10-03 08:46 UTC, 4tyTwo commented on chat/apps/chat_server/src/chat_server_sup.erl
> +    ok = lager:notice("Launched cowboy on ~p:~p", [Host, Port]),
Эффекта, что я лишний раз прокидываю значения и создаю возможность передать супервайзеру что угодно? Как я догадываюсь, get_env тогда лучше поместить уже внутрь супервайзера?

2018-10-03 10:17 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_sup.erl
> +    ok = lager:notice("Launched cowboy on ~p:~p", [Host, Port]),
Не, я не про это, но это тоже здравая мысль.

Я про то, что для ковбоя значит передача, допустим, `"localhost"` в качестве `Host` в https://github.com/rbkmoney/erlang-school/pull/12/files/382719d08c3efe7e13de3515c956b333a9f71256..f65f695ff7a4b1a6567d21a26c94185566ac2c72#diff-de5ccf0a0c337248abd5e2b85378d33fR34 ?

2018-10-03 10:45 UTC, 4tyTwo commented on chat/apps/chat_server/src/chat_server_sup.erl
> +    ok = lager:notice("Launched cowboy on ~p:~p", [Host, Port]),
Никакой нормальной информации по хосту в документах ковбоя не нашел, но знаю, что если указать '"localhost"', to подключиться можно будет только по 'localhost:port', а если в качестве хоста указать ''_'', то можно и по 'localhost:port' и '127.0.0.1:port' и по локальному ip. Лучше поставить андерскор в качестве хоста?

2018-10-03 11:37 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_sup.erl
> +    ok = lager:notice("Launched cowboy on ~p:~p", [Host, Port]),
Не совсем, тут нужно понимать, что есть _хост_, на котором будет открываться слушающий (_listening_) сокет, а есть _хост_ из [спецификации HTTP](https://tools.ietf.org/html/rfc7230#section-5.4), и используются они для разных задач. Ты на https://github.com/rbkmoney/erlang-school/pull/12/files/382719d08c3efe7e13de3515c956b333a9f71256..f65f695ff7a4b1a6567d21a26c94185566ac2c72#diff-de5ccf0a0c337248abd5e2b85378d33fR34 указываешь именно второй _хост_.

> Никакой нормальной информации по хосту в документах ковбоя не нашел, но знаю, что если указать "localhost", to подключиться можно будет только по localhost:port

При этом то, о чём ты говоришь, к уровню HTTP отношения _ещё_ не имеет, это уровень TCP, и в случае с ковбоем/рэнчем тебе нужно обращаться вот в [этот кусок](https://ninenines.eu/docs/en/ranch/1.6/manual/ranch_tcp/) документации.

2018-10-03 13:25 UTC, 4tyTwo commented on chat/apps/chat_server/src/chat_server_sup.erl
> +    ok = lager:notice("Launched cowboy on ~p:~p", [Host, Port]),
Ок, в моем конкретном случае речь идет о _хосте_ для _слушающего_, тем не менее я так и не понимаю его связи с хостом из http

2018-10-03 13:54 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_sup.erl
> +    ok = lager:notice("Launched cowboy on ~p:~p", [Host, Port]),
Тогда тебе нужно вот эта

```
ip
    Interface to listen on. Listen on all interfaces by default.
```

из возможных опций `ranch_tcp`, которые можно скормить в виде `TransportOpts` третьим аргументом `ranch:child_spec/5`.

2018-10-03 14:00 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_sup.erl
> +    ok = lager:notice("Launched cowboy on ~p:~p", [Host, Port]),
> не понимаю его связи с хостом из http

Её на самом деле можно сказать и нет. Значение заголовка `Host` в HTTP традиционно используется для задачи _как бы так отделить трафик на сайт example.org от трафика на admin.example.org, когда у них один и тот же ip адрес и tcp порт_. Именно благодаря возможности засунуть некое значение `Host` в `cowboy_router:compile/1` ты бы мог решить эту задачу. Однако из-за того, что ты думал, что это _хост_ в смысле TCP/IP, это бы повело себя совершенно по-другому: сервер бы слушал на _всех_ сетевых интерфейсах, однако если бы ты делал к серверу запросы вида `http://127.0.0.1/` отдавали бы `404 Not Found`, только запросы вида `http://localhost/` завершались бы успешно.

2018-10-04 14:22 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_sup.erl
> +        {error, _} ->
Вот это кстати с точки зрения оператора твоей системы не самое удачное поведение. Даже тупо упасть с badmatch было мне кажется правильнее.

2018-10-04 14:23 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_sup.erl
> +        {error, _} ->
Лучше в таком случае воспользоваться функцией `application:get_env/3`, которая даёт возможность задать default value.

2018-10-04 14:23 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_sup.erl
> +            [Ip] = HostMap#hostent.h_addr_list;
А если там больше одного IP будет? )

2018-10-10 08:54 UTC, keynslug commented on chat/apps/library/src/library_alt_protocol.erl
> +-type succ_message() :: {event(), user(), room()}.
Кстати, `succ` применительно к практике функциональных языков обычно обозначает _successor_. 🙃

2018-10-10 09:09 UTC, keynslug commented on chat/apps/library/src/library_alt_protocol.erl
> +-type decoded() :: succ_message() | error_reason().
А почему не назвать просто `message()`? Когда ты называешь тип `decoded()`, складывается ощущение, что в твоём приложении данные на проводе _первичны_ относительно термов в рантайме.

2018-10-10 09:09 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_message_handler.erl
> +send_error_message(not_exists) ->
Лол, а почему не просто
```
send_error_message(Reason) ->
    chat_server_ws_handler:send({error, Reason}, self());
```
?

2018-10-10 09:09 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_sup.erl
> +    ok = lager:debug("Application will run on ~p, port ~p", [IpList, Port]),
Но ведь это неправда, он только на первом `Ip` из списка запустится. )

2018-10-10 09:09 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_sup.erl
> +    ok = lager:debug("Host received: ~p~nPort received ~p", [Host, Port]),
Вот тут я конечно не вижу потребности перенос строки вставлять посреди лог-сообщения. Ты представляешь же как это в логах будет выглядеть с дефолтным форматтером?

2018-10-10 09:09 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_sup.erl
> +    {ok, HostRec} = inet:gethostbyname(Host),
Нет ли ощущения, что вот эти три строчки заслуживают вынесения в отдельную минифункцию с прост и чётко определяемой ответственностью?

2018-10-10 09:09 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_sup.erl
> +                                    http,
Жёсткая индентация конечн.

2018-10-10 09:34 UTC, 4tyTwo commented on chat/apps/chat_server/src/chat_server_sup.erl
> +                                    http,
А есть какой-нибудь гайд по правильной индентации таких случаев?  
Я ориентировался на похожий способ из кода machinegun'а  
https://github.com/rbkmoney/machinegun/blob/master/apps/mg/src/mg_storage_pool.erl
```
start_link(#{worker := Worker}, RegName) ->
    mg_utils_supervisor_wrapper:start_link(
        RegName,
        #{strategy => simple_one_for_one},
        [
            fix_restart_type(mg_storage:child_spec(Worker, worker))
        ]
    ).
```
Или загвоздка в том, что у меня аргументы на один таб дальше чем открывающая скобка?

2018-10-10 09:36 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_sup.erl
> +                                    http,
Лол, я всё это время думал, что ты вот по [этим правилам|https://github.com/rbkmoney/erlang-guidelines/blob/master/code-style.md#%D0%A4%D0%BE%D1%80%D0%BC%D0%B0%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5] работал. А тут как разнесло.

2018-10-10 11:13 UTC, 4tyTwo commented on chat/apps/chat_server/src/chat_server_sup.erl
> +                                    http,
Я читал их, как и гайдлайн от inaka, и старался следовать, но рекомендации из этих гайдов вроде не покрывают моего случая.

2018-10-11 13:09 UTC, keynslug reviewed
Мелкие замечания по свежим изменениям.

2018-10-11 13:09 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_sup.erl
> +    {ok, HostRec} = inet:gethostbyname(Host),
На самом деле я имел ввиду строчки с:
```
    {ok, HostRec} = inet:gethostbyname(Host),
    IpList = HostRec#hostent.h_addr_list,
    [Ip | _] = IpList, % Assume that needed IP is first, idk how we should behave with multiple IPs
```
🙃

2018-10-11 13:09 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_sup.erl
>      ok = lager:notice("Launched cowboy on ~p:~p", [Host, Port]),
На самом деле он не запущен ещё, ты только childspec здесь сконструировал.

2018-10-11 13:09 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_sup.erl
>              {"/static/[...]", cowboy_static, {priv_dir, chat_server, "static"}}
Вот тут интересный пример по поводу индентации.

> уровень вложенности выражения напрямую зависит от его глубины в синтаксическом дереве, при этом начало и окончание (когда применимо) всегда находятся на одном уровне индентации, а содержимое, в случае необходимости разбивки на строки, – на следующем.

Тут конечно неочевидно что значит _глубина в синтаксическом дереве_, но моё соображение заключалось в том, что если тебе нужно разбить выражение на строки, то это могло бы выглядеть вот так:

```
    Dispatch = cowboy_router:compile([
        {'_', [
            {"/", cowboy_static, {priv_file, chat_server, "index.html"}},
            {"/websocket", chat_server_ws_handler, []},
            {"/static/[...]", cowboy_static, {priv_dir, chat_server, "static"}}
        ]}
    ]),
```

Или вот так:

```
    Dispatch = cowboy_router:compile([
        {'_', 
            [
                {"/", cowboy_static, {priv_file, chat_server, "index.html"}},
                {"/websocket", chat_server_ws_handler, []},
                {"/static/[...]", cowboy_static, {priv_dir, chat_server, "static"}}
            ]
        }
    ]),
```

2018-10-11 13:09 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_sup.erl
> +                    http,
По поводу индентации докоп пока сохраняется, если ты следуешь вот этим [гайдлайнам](https://github.com/rbkmoney/erlang-guidelines/blob/master/code-style.md#%D0%A4%D0%BE%D1%80%D0%BC%D0%B0%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5). Если да, то налицо нефиксированный размер отступа: везде 4 пробела, а здесь почему-то 16.

2018-10-11 13:15 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_message_handler.erl
> +    chat_server_ws_handler:send({error, Reason}, self()).
Опа-па, у вас циклическая зависимость.

`chat_server_ws_handler` явно дёргает `chat_server_message_handler`, а он в свою очередь явно дёргает `chat_server_ws_handler`.

Обычно это сигнализирует о некорректном разделении ответственности между двумя кусками кода. Здесь я вижу одно очевидное решение: сделать сигнатуру `-spec handle_message(message(), state()) -> {ok, state()} | {error, ..}.`

2018-10-11 13:18 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_message_handler.erl
> +    chat_server_ws_handler:send({error, Reason}, self()).
На самом деле похожий вопрос возникает и по поводу того, что `gproc_ps` используется здесь, а результирующие сообщения обрабатываются на уровень выше.

2018-10-11 13:28 UTC, keynslug reviewed
Весёлое минизадание, я подозреваю что он сможет обнаружить по крайней мере один небольшой косяк в коде, если я конечно правильно всё понял. Даже если нет, минизадание-то весёлое 💃 .

2018-10-11 13:28 UTC, keynslug commented on chat/apps/chat_server/test/server_SUITE.erl
> +-type groupName() :: atom().
🐫 ?

2018-10-11 13:28 UTC, keynslug commented on chat/apps/chat_server/test/server_SUITE.erl
> +     [mega_test].
Есть предложение сконструировать здесь ещё один, _рандомизированный_ тест с _несколькими клиентами_, в идеале конечно конкуррентными, но это уже сложнее. Суть теста в том, чтобы убедиться, что все валидные с точки зрения клиентов state transitions обрабывается корректно (опять же в контексте теста это значит, что клиенты не должны плеваться неожидаемыми ответами, например, какими-нибудь дикими исключениями).

Рандомизированность его может заключаться в том, что клиенты будут осуществлять _случайный_ набор действий из всех дозволенных протоколом. За вдохновением можно обратиться к статье о [цепях Маркова](https://en.wikipedia.org/wiki/Markov_chain). При этом чтобы тест был честным, клиенты должны долбить какое-то количество _общих_ ресурсов, в данном случае например, одну или ограниченный набор заранее заданных комнат.

2018-10-16 17:02 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_ws_handler.erl
> +            send(ErrorMessage, self()),
Не очень понятно, почему бы сразу `reply` не сделать.

2018-10-16 17:02 UTC, keynslug commented on chat/apps/library/src/library_protocol.erl
> +-export_type([error_reason/0]).
Не вижу, где он теперь используется.

2018-10-16 17:08 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_message_handler.erl
> +-type subscribers() :: chat_server_ws_handler:state().
Опять циклическая зависимость кажется подъехала, не? )

2018-10-16 17:08 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_message_handler.erl
> +            gproc_ps:publish(l, Room, room_deleted), % Unsubscribe everyone
А зачем два разных сообщения, говорящие об одном и том же?

2018-10-16 17:29 UTC, keynslug commented on chat/apps/chat_server/test/test_bot.erl
> +get_node(Action) ->
Вообще линтеры и стайлгайды обычно топят больше за function clauses, чем case clauses.

2018-10-16 17:29 UTC, keynslug commented on chat/apps/chat_server/test/test_bot.erl
> +	lists:nth(Index, Rooms).
Чёт с индентацией.

2018-10-16 17:29 UTC, keynslug commented on chat/apps/chat_server/test/test_bot.erl
> +-spec create_noice() ->
Noise видимо имелся ввиду? )

2018-10-16 17:29 UTC, keynslug commented on chat/apps/chat_server/test/server_SUITE.erl
> +randomized_multiclient_test(_C) ->
Топ!

Правда ты не дожидаешься никаких результатов исполнения, потому что единственное что ты делаешь в рамках тестового _процесса_ – спавнишь ботов. Поэтому этот тест всегда будет успешно проходить.

За вдохновением и разъяснениями можно вот [сюда](https://github.com/rbkmoney/genlib/blob/master/src/genlib_pmap.erl) посмотреть.

2018-10-16 17:29 UTC, keynslug commented on chat/apps/chat_server/test/test_bot.erl
> +-type markov_node() :: #{
А что если я хочу _нулевые_ вероятности для двух или более событий задать? )

2018-10-16 17:29 UTC, keynslug commented on chat/apps/chat_server/test/test_bot.erl
> +-define(JOIN,    #{0 => create, 0.2 => join, 0.3 => message, 0.8 => leave, 0.9 => delete}).
А почему это хардкод здесь, а не в тест-сьюте?

2018-10-16 17:29 UTC, keynslug commented on chat/apps/chat_server/test/test_bot.erl
> +        {stop, no_actions_remaining};
Обрати внимание на финальный _notice_ в описании [`Module:terminate/2`](http://erlang.org/doc/man/gen_server.html#Module:terminate-2), он справедлив и в текущем случае.

2018-10-16 17:29 UTC, keynslug commented on chat/apps/chat_server/test/test_bot.erl
> +    Keys = maps:keys(MarkovNode),
Подход правильный! Проблема с такой струкутрой данных (кроме неочевидной вероятности того или иного события) ещё и в том, что _нет гарантии_ на порядок (order) ключей.

2018-10-17 12:01 UTC, 4tyTwo commented on chat/apps/chat_server/test/test_bot.erl
> +-type markov_node() :: #{
Можно задавать действию такой же числовой ключ как и предыдущему, тогда предыдущее действие не окажется в мапе. Как я понимаю у меня проблема с тем, что в описании типа `markov_node()` напрямую говорится о 5 **обязательных** парах ключ-значение?

2018-10-17 12:09 UTC, 4tyTwo commented on chat/apps/chat_server/test/test_bot.erl
> +    Keys = maps:keys(MarkovNode),
Пока не понимаю как порядок ключей влияет на что-то кроме читаемости кода, но подумаю как упростить понимание структуры и, возможно, работы с ней

2018-10-17 12:10 UTC, keynslug commented on chat/apps/chat_server/test/test_bot.erl
> +-type markov_node() :: #{
Типа того. Мне кажется более естественным представление вида `#{event() => relative_frequency()}`, где `relative_frequency() :: number()`. Или что-то близкое подобное.

2018-10-17 12:12 UTC, keynslug commented on chat/apps/chat_server/test/test_bot.erl
> +    Keys = maps:keys(MarkovNode),
А, да, верно, корректность не нарушена, это я сам просмотрел, сорьки.

2018-10-17 14:34 UTC, 4tyTwo commented on chat/apps/chat_server/test/test_bot.erl
> +-type markov_node() :: #{
Нууу, я решил просто спрятать работу с нодой в отдельный модуль, с простейшей необходимой api'шкой.

2018-10-17 15:59 UTC, 4tyTwo commented on chat/apps/chat_server/test/server_SUITE.erl
> +randomized_multiclient_test(_C) ->
Сделал коллектор для ботов, тем не менее все еще непонятно что происходит внутри ботов. По факту они создают рандомную нагрузку и мы проверяем, что сервер просто не упадет. Никакой проверки верности ответов сервера не происходит (да и непонятно как ее делать,  раз боты практически параллельно делают случайные операции).

2018-10-17 16:59 UTC, keynslug commented on chat/apps/chat_server/test/server_SUITE.erl
> +randomized_multiclient_test(_C) ->
Для начала можно положиться на принцип, когда unexpected failure на сервере порождает как следствие unexpected failure на клиенте. Тогда клиенты (здесь _боты_) по-хорошему должны бы упасть и по той же аналогии как следствие утянуть за собой весь тест-кейс.

2018-10-17 17:11 UTC, keynslug commented on chat/apps/chat_server/test/markov_node.erl
> +-module(markov_node).
Очень хорошо!

У тебя нет ощущения, что этот модуль можно "докрутить" до модуля `markov_chain`? 🙃 Тогда все эти `lists:zip` и выбор следующего узла лёг бы прямо сюда, что на мой взгляд ровнее бы сделало разделение ответственности между этими тремя модулями.

2018-10-17 17:11 UTC, keynslug commented on chat/apps/chat_server/test/markov_node.erl
> +-type markov_node() :: #{
Кстати, если ты хочешь сделать это представление _деталями реализации_ модуля, его не помешает отметить не как `-type markov_node() :: ...`, а как `-opaque markov_node() :: ...`. Что [заставит диалайзер][1] бить по рукам всех, кто в других модулях пытается положиться на структуру термов такого типа.

[1]: http://erlang.org/doc/reference_manual/typespec.html#type-declarations-of-user-defined-types

2018-10-17 17:11 UTC, keynslug commented on chat/apps/chat_server/test/markov_node.erl
> +round(Number, Precision) ->
А зачем здесь округление?

2018-10-17 17:11 UTC, keynslug commented on chat/apps/chat_server/test/markov_node.erl
> +-type event_possibility_map() :: #{
Кстати, если ты хочешь ужесточить проверку требований к типам во всех клиентах этого модуля, можно попробовать объявить все типы здесь как _параметризированные_, например:

```
-type event_possibility_map(T) :: #{
    T := float(),
    T => float()
}.
```

Если в функции-конструкторе также связать входы и выходы одной _переменной типа_ `T`, а в модуле с ботом затребовать `markov_node(join | ...)`, то возможно диалайзер сможет отловить нарушения подобного контракта.

2018-10-18 08:37 UTC, 4tyTwo commented on chat/apps/chat_server/test/markov_node.erl
> +round(Number, Precision) ->
Всплывают не самые красивые артефакты по типу 0.30000000000000000000000004.
Фактически они ни на что не влияют, но неприятно.

2018-10-18 08:55 UTC, keynslug commented on chat/apps/chat_server/test/markov_node.erl
> +round(Number, Precision) ->
Я пока даже не понимаю, как ты это увидел. )

2018-10-18 09:02 UTC, keynslug commented on chat/apps/chat_server/test/test_bot.erl
> +    {ok, PID} = chat_client_client:start("localhost", 8080),
Ай-яй, нарушаем, опять хардкод. 👮 

Самая здравая практика по моему опыта, которая всегда или почти всегда работает в перспективе на пользу – это вываливание всех опций текущего и зависимых компонентов наружу. Ещё в пару к ней поставляются разумные дефолты для тех параметров, где это возможно. В твоём случае я вижу, что можно `client_opts()` и тот таймаут, который в `generate_timeout/0` генерится, вывалить в опции текущего компонента. Кроме всего того, что тут уже есть.

2018-10-18 09:02 UTC, keynslug commented on chat/apps/chat_server/test/test_bot.erl
> +init({Name, ActionsLeft, Rooms, Nodes}) ->
4 на мой вкус – уже повод в мапу трансформировать опции компонента. )

2018-10-22 13:58 UTC, keynslug reviewed
Вот ещё чем бы не помешало дополнить твой `rebar.config`, чтобы диалайзер стал ещё _злее_.

```
{dialyzer, [
    {warnings, [
        % mandatory
        unmatched_returns,
        error_handling,
        race_conditions,
        unknown
    ]},
    ...
```

2018-10-22 13:58 UTC, keynslug commented on chat/apps/chat_server/test/test_bot.erl
> --spec generate_timeout() ->
Можно было бы кстати в качестве `timeout` требовать у клиента 2-tuple `{Timeout, Spread}` и передавать их  в качестве параметров в эту функцию.

2018-10-22 13:58 UTC, keynslug commented on chat/apps/chat_server/test/test_bot.erl
> +    con_opts := con_opts(),
А почему кстати не `client_opts()`?

2018-10-22 13:58 UTC, keynslug commented on chat/apps/chat_server/test/test_bot.erl
>  -type req_nodes() :: #{
А как бы ты назвал этот тип по-русски?

2018-10-22 13:58 UTC, keynslug commented on chat/apps/chat_server/test/markov_node.erl
> +    ok = lager:debug("Keys: ~p, Value: ~p", [Keys, Value]),
Вот этот бы твой подход я обсудил устно как-нибудь.

2018-10-22 13:58 UTC, keynslug commented on chat/apps/chat_server/test/markov_node.erl
> +-type markov_node(T) :: #{
А этот тип не заслужил `opaque` квалификатор?

2018-10-22 13:58 UTC, keynslug commented on chat/apps/chat_server/test/markov_chain.erl
> +            {error, node_undefined} % Maybe it's better to call error(node_undefined)
Мне кажется странным, что подобные ошибочные ситуации не обработались уже на этапе `create/1`, раз он здесь есть.

2018-10-22 14:01 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_ws_handler.erl
>  websocket_info({send, Message}, Subs) ->
А зачем тебе вот этот обработчик?

2018-10-22 14:01 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_ws_handler.erl
> +websocket_info({gproc_ps_event, _Room, Message} = GprocEvent, Subs) ->
Последний оплот циклических зависимостей – матч на `gproc_ps_event`, работа с которым идёт в модуле на уровень ниже.

2018-10-23 08:33 UTC, 4tyTwo commented on chat/apps/chat_server/test/test_bot.erl
>  -type req_nodes() :: #{
Счетчиком/количеством действий.

2018-10-23 08:51 UTC, 4tyTwo commented on chat/apps/chat_server/src/chat_server_ws_handler.erl
> +websocket_info({gproc_ps_event, _Room, Message} = GprocEvent, Subs) ->
Если я в `websocket_info` буду ловить **все, что угодно**, а разбираться что эт, и обрабатывать это буду уже в `message_handler`, то это будет считаться за устранение зависимости?

2018-10-23 08:57 UTC, 4tyTwo commented on chat/apps/chat_server/test/test_bot.erl
>  -type req_nodes() :: #{
А, ты наверное про `timeout`. Тогда я бы назвал его задеркой (`delay`)

2018-10-23 11:20 UTC, keynslug commented on chat/apps/chat_server/test/test_bot.erl
>  -type req_nodes() :: #{
Не, я вообще про `req_nodes()`, я же на 26-ю строку комментнул. 🙃

2018-10-23 11:20 UTC, keynslug commented on chat/apps/chat_server/test/test_bot.erl
>  -type req_nodes() :: #{
> А, ты наверное про timeout. Тогда я бы назвал его задеркой (delay)

И кстати да, саморевью дельное.

2018-10-23 11:21 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_ws_handler.erl
> +websocket_info({gproc_ps_event, _Room, Message} = GprocEvent, Subs) ->
Да, как вариант.

2018-10-23 16:13 UTC, keynslug commented on chat/apps/chat_server/test/markov_chain.erl
> +                error(invalid_node_map)
Теперь у тебя аж 2 сценария сигнализации об ошибке во входных данных:
* `{error, Reason}` как результат вызова;
* исключение `error:invalid_node_map`.

2018-10-23 16:15 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_ws_handler.erl
>              error(unknown_message)
А не проще тогда `badmatch` словить? Тогда этот `case` был бы не нужен.

2018-10-25 09:53 UTC, keynslug commented on chat/apps/chat_server/test/markov_chain.erl
> +    AllKeys = lists:umerge(lists:map(fun maps:values/1, Nodes)),
Мне не очень импонирует подход, который аж два adt пытается скрестить. Я бы предложил:
* либо обойтить adt set: просто сделать union из всех множеств ключей нод,
* либо обойтись adt list: например, запихнуть `lists:usort/1` в подходящем месте.

2018-10-25 09:53 UTC, keynslug commented on chat/apps/chat_server/test/markov_chain.erl
> +    lists:foldl(F, NodeMap, UniqueKeys),
Концептуально вышло сложнее, чем должно было: тебе же нужно убедиться, что _все_ элементы удовлетворяют предикату, для этого есть например `lists:all/2`.

2018-10-25 09:53 UTC, keynslug commented on chat/apps/chat_server/test/markov_chain.erl
>  check_correctness(NodeMap) -> % Пока совершено монструозная конструкция, подумаю над тем, как улучшить ее
Интересно, не подошёл бы тебе `digraph` для этого задачи. 🤔

2018-10-25 09:53 UTC, keynslug commented on chat/apps/chat_server/test/server_SUITE.erl
> +    lists:map(ColProc, PIDs),
Если тебе не важен результат, то почему `map`, а не `foreach`?

2018-10-25 09:53 UTC, keynslug commented on chat/apps/chat_server/test/server_SUITE.erl
>  monitor(Vars) ->
Кажется, название функции недостаточно хорошо выражает смысл происходящего.

2018-10-25 09:53 UTC, keynslug commented on chat/apps/chat_server/src/chat_server_ws_handler.erl
>      case EventBody of
Если остался один клоз, возникает вопрос: зачем вообще `case`? 🤔

2018-10-25 09:56 UTC, keynslug commented on chat/apps/chat_server/test/markov_chain.erl
> +    markov_chain(T) | no_return().
О, а это почему здесь появилось кстати?

2018-10-25 09:58 UTC, keynslug commented on chat/apps/chat_server/test/test_bot.erl
> +    con_opts := con_opts(),
Всё ещё не понятно. 😔

2018-10-25 09:59 UTC, keynslug commented on chat/apps/chat_server/test/test_bot.erl
> --spec generate_timeout() ->
Так и вот. 🙃

2018-10-25 10:03 UTC, 4tyTwo commented on chat/apps/chat_server/test/markov_chain.erl
> +    markov_chain(T) | no_return().
Потому-что функция может выкинуть ошибку, я так понимаю что именно для таких случаев и существует `no_return()`.
Может тогда лучше все проверки вынести в функцию `check_correctness`?

2018-10-25 11:12 UTC, 4tyTwo commented on chat/apps/chat_server/test/markov_chain.erl
>  check_correctness(NodeMap) -> % Пока совершено монструозная конструкция, подумаю над тем, как улучшить ее
Теоретически подходит, цепь Маркова ведь можно представить как ориентированный граф. Тогда проверкой корректности служит проверка отсутствия вершин с нулевой степенью.
Исходя из поверхностного знакомства с модулем`digraph`, я бы сказал, что решить задачу с его помощью можно, но довольно нудно и точно не проще, чем просто проверкой ключей.

2018-10-25 12:26 UTC, keynslug commented on chat/apps/chat_server/test/markov_chain.erl
> +    markov_chain(T) | no_return().
Я так понимаю, с точки зрения диалайзера в анализе функции заявленной с `no_return()` его волнует в первую очередь одна вещь – вернёт ли функция хоть что-то на _заявленных типах аргументов_. То есть в данном случае вроде как её и не надо `no_return()` помечать, потому как формально любой `markov_chain(T)` является валидным, нам просто нужно в этом убедиться.

2018-10-25 12:33 UTC, keynslug commented on chat/apps/chat_server/test/markov_chain.erl
> +    Keys = lists:umerge(lists:map(fun maps:values/1, Nodes)),
Долго не мог понять, что за подвох, как будто я что-то унюхял, а вот что: `markov_node(_)` же opaque, чегой-то ты в неё с `maps:values/1` лезешь?

2018-10-25 12:33 UTC, keynslug commented on chat/apps/chat_server/test/markov_chain.erl
> +    Keys = lists:umerge(lists:map(fun maps:values/1, Nodes)),
Круто! Я только не понял, почему ты используешь `umerge`, если списки неотсортированные. )

2018-10-25 12:33 UTC, keynslug commented on chat/apps/chat_server/test/markov_chain.erl
>  create(NodesMap, InitialNode) ->
Кстати, разве `InitialNode :: markov_node:markov_node(T)`, а не просто `InitialNode :: T`?

2018-10-25 12:44 UTC, 4tyTwo commented on chat/apps/chat_server/test/markov_chain.erl
> +    Keys = lists:umerge(lists:map(fun maps:values/1, Nodes)),
То есть, если мне нужен такой функционал, то надо реализовать его в api `markov_node`?

2018-10-25 13:03 UTC, 4tyTwo commented on chat/apps/chat_server/test/markov_chain.erl
> +    markov_chain(T) | no_return().
Тогда получается `no_return()` нужно указывать только если функция должна крашнуться именно на определенном наборе аргументов?
То есть что-то вида:
`atom_to_int(atom()) -> integer();
  foo(string()) -> no_return()`

2018-10-25 13:05 UTC, keynslug commented on chat/apps/chat_server/test/markov_chain.erl
> +    Keys = lists:umerge(lists:map(fun maps:values/1, Nodes)),
Угу.

2018-10-25 13:12 UTC, keynslug commented on chat/apps/chat_server/test/markov_chain.erl
> +    markov_chain(T) | no_return().
Сложно чётко ответить, я думаю, твой пример на практике в любом случае выглядел бы как `-spec atom_to_int(atom()) -> integer().`, несмотря на всё то богатство термов, которыми в эту функцию можно стрельбануть в рантайме. Как я это сейчас себе представляю, диалайзер берёт на себя проверку того, что кто бы в неё чем не стрельбанул в коде, то это либо `atom()`, либо _непойми-что_. Но если он точно знает, что это `string()`, то это должно быть ошибкой проверки типов.

Первая (и в идеале последняя, но этот идеал практически недостижим) причина помечать функцию `no_return()` – это если та крутится в бесконечной рекурсии.

2018-10-25 13:26 UTC, 4tyTwo commented on chat/apps/chat_server/test/markov_chain.erl
> +    markov_chain(T) | no_return().
Отлично, думаю я понял кейсы использования этого типа, и понял, что он в моем проекте нигде не нужен.

2018-10-25 14:17 UTC, 4tyTwo commented on chat/apps/chat_server/test/test_bot.erl
> --spec generate_timeout() ->
Наконец-то сделал это

2018-10-26 13:04 UTC, keynslug approved these changes

2018-12-19 08:30 UTC, closed without merging